import Foundation

struct AgentBundleRequest: Codable, Equatable {
    var title: String
    var task: String?
    var q: String?
    var type: ResourceType?
    var ids: [UUID]?
    var includeClipboard: Bool?
    var includeSensitiveClipboard: Bool?
    var limit: Int?
    var tags: [String]?
    var source: String?
    var pinned: Bool?
}

enum AgentBundleError: Error {
    case missingTitle
    case missingSelection
    case noMatches
}

struct AgentBundle {
    static let group = "Agent Bundles"
    static let defaultLimit = 12
    static let maxLimit = 30
    static let excerptLimit = 900

    static func makeResource(from request: AgentBundleRequest, resources: [ResourceItem], now: Date = Date()) throws -> (item: ResourceItem, included: [ResourceItem]) {
        let title = request.title.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !title.isEmpty else {
            throw AgentBundleError.missingTitle
        }

        let query = (request.q ?? request.task)?
            .trimmingCharacters(in: .whitespacesAndNewlines)
            .nilIfEmpty
        let ids = request.ids ?? []
        guard !ids.isEmpty || query != nil else {
            throw AgentBundleError.missingSelection
        }

        let visibility = AgentClipboardVisibility(
            includeClipboard: request.includeClipboard ?? false,
            includeSensitiveClipboard: request.includeSensitiveClipboard ?? false
        )
        let typedVisibleResources = resources
            .filter(visibility.allows)
            .filter { item in
                request.type.map { item.type == $0 } ?? true
            }
        let matchedResources = selectedResources(from: typedVisibleResources, ids: ids, query: query)
        let appliedLimit = request.limit.map { min(max(1, $0), maxLimit) } ?? defaultLimit
        let included = Array(matchedResources.prefix(appliedLimit))

        guard !included.isEmpty else {
            throw AgentBundleError.noMatches
        }

        let content = markdown(
            title: title,
            query: query,
            type: request.type,
            visibility: visibility,
            included: included,
            now: now
        )
        let item = ResourceItem(
            type: .knowledge,
            group: group,
            title: title,
            content: content,
            tags: bundleTags(request.tags, query: query),
            source: request.source ?? "Agent Bundle",
            pinned: request.pinned ?? true,
            createdAt: now,
            updatedAt: now
        )

        return (item, included)
    }

    private static func selectedResources(from resources: [ResourceItem], ids: [UUID], query: String?) -> [ResourceItem] {
        let selected: [ResourceItem]
        if !ids.isEmpty {
            selected = ids.compactMap { id in
                resources.first { $0.id == id }
            }
        } else if let query {
            selected = resources.filter { matches($0, query: query) }
        } else {
            selected = []
        }

        return selected.sorted { lhs, rhs in
            if lhs.pinned != rhs.pinned {
                return lhs.pinned && !rhs.pinned
            }

            return lhs.updatedAt > rhs.updatedAt
        }
    }

    private static func matches(_ item: ResourceItem, query: String) -> Bool {
        let tokens = searchTokens(query)
        guard !tokens.isEmpty else {
            return false
        }

        let haystack = ([item.title, item.group, item.content] + item.tags)
            .joined(separator: " ")
            .lowercased()
        return tokens.allSatisfy { haystack.contains($0) }
    }

    private static func markdown(
        title: String,
        query: String?,
        type: ResourceType?,
        visibility: AgentClipboardVisibility,
        included: [ResourceItem],
        now: Date
    ) -> String {
        var lines: [String] = [
            "# \(title)",
            "",
            "Generated by DingDong Agent Bundle at \(timestamp(now)).",
            "Task/query: \(query ?? "manual selection")",
            "Type filter: \(type?.rawValue ?? "all")",
            "Clipboard included: \(visibility.includeClipboard)",
            "Sensitive clipboard included: \(visibility.includeSensitiveClipboard)",
            "Included resources: \(included.count)",
            ""
        ]

        for item in included {
            lines.append("## [\(item.type.rawValue)] \(item.title)")
            lines.append("- id: \(item.id.uuidString)")
            lines.append("- group: \(item.group)")
            lines.append("- pinned: \(item.pinned)")
            lines.append("- tags: \(item.tags.joined(separator: ", "))")
            lines.append("- updatedAt: \(timestamp(item.updatedAt))")
            lines.append("")
            lines.append(excerpt(item.content))
            lines.append("")
        }

        return lines.joined(separator: "\n")
    }

    private static func bundleTags(_ tags: [String]?, query: String?) -> [String] {
        var values = ["agent-bundle", "bundle"]
        if let query {
            values.append(contentsOf: searchTokens(query).prefix(6).map { "task:\($0)" })
        }

        values.append(contentsOf: tags ?? [])
        var seen: Set<String> = []
        return values
            .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
            .filter { !$0.isEmpty && seen.insert($0).inserted }
    }

    private static func searchTokens(_ query: String) -> [String] {
        let separators = CharacterSet.alphanumerics.inverted
        let tokens = query
            .lowercased()
            .components(separatedBy: separators)
            .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
            .filter { $0.count >= 2 }

        return Array(NSOrderedSet(array: tokens)) as? [String] ?? []
    }

    private static func excerpt(_ content: String) -> String {
        let trimmed = content.trimmingCharacters(in: .whitespacesAndNewlines)
        guard trimmed.count > excerptLimit else {
            return trimmed
        }

        return String(trimmed.prefix(excerptLimit)) + "\n[truncated]"
    }

    private static func timestamp(_ date: Date) -> String {
        let formatter = ISO8601DateFormatter()
        formatter.formatOptions = [.withInternetDateTime, .withFractionalSeconds]
        return formatter.string(from: date)
    }
}

private extension String {
    var nilIfEmpty: String? {
        isEmpty ? nil : self
    }
}
