import Foundation

struct AgentCapabilityManifest {
    static func object() -> [String: Any] {
        [
            "service": "DingDong",
            "baseURL": "http://127.0.0.1:8765",
            "transport": "loopback-http",
            "resourceTypes": ResourceType.allCases.map(\.rawValue),
            "sounds": DingSound.apiValues,
            "limits": [
                "clipboardHistory": ResourceStore.clipboardRetentionPolicy().maxItems,
                "clipboardRetentionDays": ResourceStore.clipboardRetentionPolicy().maxAgeDays,
                "resourceContentCharacters": ResourceLimits.maxResourceContentCharacters,
                "clipboardContentCharacters": ResourceLimits.maxClipboardContentCharacters,
                "agentEvents": AgentEventStore.maxEvents,
                "activeAgents": AgentPresenceStore.maxAgents,
                "knowledgeIndexFiles": KnowledgeIndexer.defaultMaxFiles,
                "libraryImportItems": LibraryImporter.maxLimit
            ],
            "features": [
                "cheerfulReminderSound",
                "localSynthesizedChimes",
                "builtInSoundThemes",
                "systemStatus",
                "performanceStatus",
                "agentDiscoveryManifest",
                "menuBarIconFlash",
                "menuBarUnreadBadge",
                "customSound",
                "resourceLibrary",
                "resourceLibraryExport",
                "resourceGroupSummary",
                "clipboardCapture",
                "clipboardMonitoring",
                "clipboardClassification",
                "clipboardOverview",
                "clipboardInsights",
                "clipboardDigest",
                "clipboardCollection",
                "clipboardHistory",
                "clipboardGroups",
                "clipboardSnippets",
                "clipboardSnippetRestore",
                "clipboardOrganization",
                "clipboardHistoryPrivacyGuard",
                "sensitiveClipboardDetection",
                "sensitiveClipboardAgentGuard",
                "clipboardPromotion",
                "clipboardRestore",
                "knowledgeIndexing",
                "agentStartupBrief",
                "agentStartupPack",
                "agentMinimalBridge",
                "agentPreparePack",
                "agentWorkbench",
                "agentInstructionPack",
                "agentPresence",
                "agentSessions",
                "agentSessionUpdates",
                "agentSessionFilters",
                "agentMemories",
                "agentMemoryFilters",
                "agentResourceRecommendation",
                "agentResourceDetail",
                "agentResourceResolve",
                "agentResourceBundles",
                "agentHandoffNotes",
                "agentHandoffStatusUpdates",
                "agentHandoffStatusFilters",
                "agentContextPack",
                "agentToolkitPrompt",
                "uiTabDeepLink",
                "bulkImport",
                "agentTemplates",
                "recentAgentEvents"
            ],
            "performance": [
                "clipboardMonitoring": "opt-in low-frequency polling",
                "agentPresence": "in-memory bounded active agent registry",
                "knowledgeIndexing": "on-demand bounded scan",
                "libraryImport": "direct children only with bounded item count",
                "storage": "local JSON resource store"
            ],
            "endpoints": [
                ["method": "GET", "path": "/health", "description": "Check service status"],
                ["method": "GET", "path": "/system/status", "description": "Return lightweight runtime, resource, clipboard, and performance status"],
                ["method": "POST", "path": "/ding", "description": "Trigger sound and icon flash"],
                ["method": "GET", "path": "/events", "description": "List recent agent events"],
                ["method": "GET", "path": "/agent/templates", "description": "List reusable agent command templates"],
                ["method": "GET", "path": "/agent/capabilities", "description": "Describe DingDong agent-facing capabilities"],
                ["method": "GET", "path": "/agent/manifest", "description": "Return the machine-readable local agent discovery manifest"],
                ["method": "GET", "path": "/.well-known/dingdong-agent.json", "description": "Return the same machine-readable local agent discovery manifest from a well-known path"],
                ["method": "GET", "path": "/agent/toolkit", "description": "Return copyable onboarding instructions and commands for local agents"],
                ["method": "GET", "path": "/agent/startup", "description": "Return a one-call startup brief plus task-scoped context pack"],
                ["method": "GET", "path": "/agent/bridge", "description": "Return dynamic prompt, skill, and MCP config for the minimal agent bridge"],
                ["method": "GET", "path": "/agent/prepare", "description": "Return system status, startup context, recommendations, and clipboard insights for a task"],
                ["method": "GET", "path": "/agent/workbench", "description": "Return a lightweight local agent workbench with active sessions, open handoffs, memories, and next commands"],
                ["method": "GET", "path": "/agent/instructions", "description": "Return copyable task startup instructions for local AI agents"],
                ["method": "GET", "path": "/agent/presence", "description": "List recently active local agents"],
                ["method": "POST", "path": "/agent/presence", "description": "Register or refresh a local agent status"],
                ["method": "POST", "path": "/agent/session", "description": "Create a shared active task session checkpoint for local agents"],
                ["method": "PATCH", "path": "/agent/session/{id}", "description": "Append progress, status, next actions, or resource ids to an agent session"],
                ["method": "GET", "path": "/agent/sessions", "description": "List recent agent sessions, optionally filtered by status or source"],
                ["method": "POST", "path": "/agent/memory", "description": "Save a durable local memory for future agents"],
                ["method": "GET", "path": "/agent/memories", "description": "List durable agent memories, optionally filtered by query, kind, or source"],
                ["method": "GET", "path": "/agent/brief", "description": "Return a fast startup brief for local agents"],
                ["method": "GET", "path": "/agent/recommend", "description": "Recommend shared resources for a task query"],
                ["method": "GET", "path": "/agent/resolve", "description": "Resolve the best matching shared resource and return its guarded detail in one call"],
                ["method": "GET", "path": "/agent/resource/{id}", "description": "Fetch one shared resource by id with clipboard content hidden unless explicitly included"],
                ["method": "POST", "path": "/agent/bundle", "description": "Save a reusable task bundle from matching shared resources"],
                ["method": "POST", "path": "/agent/handoff", "description": "Save an agent handoff note into the shared library"],
                ["method": "PATCH", "path": "/agent/handoff/{id}", "description": "Update handoff status, progress, source, or pinned state"],
                ["method": "GET", "path": "/agent/handoffs", "description": "List recent agent handoff notes, optionally filtered by status"],
                ["method": "GET", "path": "/agent/context", "description": "Return a bounded local context pack for agents"],
                ["method": "GET", "path": "/library", "description": "List/search shared resources"],
                ["method": "GET", "path": "/library/groups", "description": "List shared resource groups with counts"],
                ["method": "GET", "path": "/library/export", "description": "Export a bounded resource library snapshot with clipboard excluded by default"],
                ["method": "POST", "path": "/library", "description": "Create a shared resource"],
                ["method": "PATCH", "path": "/library/{id}", "description": "Edit, pin, or unpin a resource"],
                ["method": "DELETE", "path": "/library/{id}", "description": "Delete a resource"],
                ["method": "POST", "path": "/library/import", "description": "Bulk import resources from a folder"],
                ["method": "GET", "path": "/clipboard/overview", "description": "Return clipboard classification counts, groups, and tags without content"],
                ["method": "GET", "path": "/clipboard/insights", "description": "Return clipboard metadata insights, candidates, and agent action recommendations without content"],
                ["method": "GET", "path": "/clipboard/digest", "description": "Return task-scoped clipboard candidates, groups, and agent actions with content hidden by default"],
                ["method": "POST", "path": "/clipboard/collect", "description": "Save task-scoped clipboard records as a reusable knowledge collection with sensitive items hidden by default"],
                ["method": "GET", "path": "/clipboard/history", "description": "List clipboard history metadata with optional explicit content access"],
                ["method": "GET", "path": "/clipboard/snippets", "description": "List clipboard records tagged with alias:name for quick reuse"],
                ["method": "GET", "path": "/clipboard/groups", "description": "List clipboard groups and classification overview"],
                ["method": "PATCH", "path": "/clipboard/{id}", "description": "Edit clipboard title, group, tags, or pinned state without changing content"],
                ["method": "POST", "path": "/clipboard/capture", "description": "Capture current text clipboard"],
                ["method": "POST", "path": "/clipboard/promote/{id}", "description": "Promote a clipboard record into a shared AI resource"],
                ["method": "POST", "path": "/clipboard/restore/{id}", "description": "Restore a clipboard history record to the system clipboard"],
                ["method": "POST", "path": "/clipboard/snippet/{alias}/restore", "description": "Restore the newest pinned clipboard snippet with a matching alias tag"],
                ["method": "POST", "path": "/clipboard/monitor", "description": "Toggle clipboard monitoring"],
                ["method": "GET", "path": "/knowledge/index", "description": "Scan local knowledge path summaries"],
                ["method": "POST", "path": "/ui/show", "description": "Open DingDong panel, optionally with tab=today, library, clipboard, or api"]
            ]
        ]
    }
}
