import Foundation

struct ClipboardCollectionRequest: Codable, Equatable {
    var title: String
    var task: String?
    var q: String?
    var ids: [UUID]?
    var includeSensitiveClipboard: Bool?
    var limit: Int?
    var tags: [String]?
    var source: String?
    var pinned: Bool?
}

enum ClipboardCollectionError: Error {
    case missingTitle
    case missingSelection
    case noMatches
}

struct ClipboardCollection {
    static let group = "Clipboard Collections"
    static let defaultLimit = 10
    static let maxLimit = 30
    static let excerptLimit = 900

    static func makeResource(from request: ClipboardCollectionRequest, clipboardItems: [ResourceItem], now: Date = Date()) throws -> (item: ResourceItem, included: [ResourceItem], hiddenSensitive: Int) {
        let title = request.title.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !title.isEmpty else {
            throw ClipboardCollectionError.missingTitle
        }

        let query = (request.q ?? request.task)?
            .trimmingCharacters(in: .whitespacesAndNewlines)
            .nilIfEmpty
        let ids = request.ids ?? []
        guard !ids.isEmpty || query != nil else {
            throw ClipboardCollectionError.missingSelection
        }

        let allClipboardItems = clipboardItems.filter { $0.type == .clipboard }
        let selected = selectedItems(from: allClipboardItems, ids: ids, query: query)
        let includeSensitive = request.includeSensitiveClipboard ?? false
        let hiddenSensitive = includeSensitive ? 0 : selected.filter(\.isSensitiveClipboard).count
        let visibleItems = includeSensitive ? selected : selected.filter { !$0.isSensitiveClipboard }
        let appliedLimit = request.limit.map { min(max(1, $0), maxLimit) } ?? defaultLimit
        let included = Array(visibleItems.prefix(appliedLimit))

        guard !included.isEmpty else {
            throw ClipboardCollectionError.noMatches
        }

        let content = markdown(
            title: title,
            query: query,
            included: included,
            includeSensitive: includeSensitive,
            hiddenSensitive: hiddenSensitive,
            now: now
        )
        let item = ResourceItem(
            type: .knowledge,
            group: group,
            title: title,
            content: content,
            tags: collectionTags(request.tags, query: query),
            source: request.source ?? "Clipboard Collection",
            pinned: request.pinned ?? true,
            createdAt: now,
            updatedAt: now
        )

        return (item, included, hiddenSensitive)
    }

    private static func selectedItems(from items: [ResourceItem], ids: [UUID], query: String?) -> [ResourceItem] {
        let selected: [ResourceItem]
        if !ids.isEmpty {
            selected = ids.compactMap { id in
                items.first { $0.id == id }
            }
        } else if let query {
            selected = items.filter { matches($0, query: query) }
        } else {
            selected = []
        }

        return selected.sorted { lhs, rhs in
            if lhs.pinned != rhs.pinned {
                return lhs.pinned && !rhs.pinned
            }

            return lhs.updatedAt > rhs.updatedAt
        }
    }

    private static func matches(_ item: ResourceItem, query: String) -> Bool {
        let tokens = searchTokens(query)
        guard !tokens.isEmpty else {
            return false
        }

        let haystack = ([item.title, item.group, item.content] + item.tags)
            .joined(separator: " ")
            .lowercased()
        return tokens.allSatisfy { haystack.contains($0) }
    }

    private static func markdown(
        title: String,
        query: String?,
        included: [ResourceItem],
        includeSensitive: Bool,
        hiddenSensitive: Int,
        now: Date
    ) -> String {
        var lines: [String] = [
            "# \(title)",
            "",
            "Generated by DingDong Clipboard Collection at \(timestamp(now)).",
            "Task/query: \(query ?? "manual selection")",
            "Sensitive clipboard included: \(includeSensitive)",
            "Hidden sensitive clipboard: \(hiddenSensitive)",
            "Included clipboard records: \(included.count)",
            ""
        ]

        for item in included {
            lines.append("## \(item.title)")
            lines.append("- id: \(item.id.uuidString)")
            lines.append("- group: \(item.group)")
            lines.append("- pinned: \(item.pinned)")
            lines.append("- tags: \(item.tags.joined(separator: ", "))")
            lines.append("- updatedAt: \(timestamp(item.updatedAt))")
            lines.append("")
            lines.append(excerpt(item.content))
            lines.append("")
        }

        return lines.joined(separator: "\n")
    }

    private static func collectionTags(_ tags: [String]?, query: String?) -> [String] {
        var values = ["clipboard-collection", "from-clipboard", "knowledge"]
        if let query {
            values.append(contentsOf: searchTokens(query).prefix(6).map { "task:\($0)" })
        }

        values.append(contentsOf: tags ?? [])
        var seen: Set<String> = []
        return values
            .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
            .filter { !$0.isEmpty && seen.insert($0).inserted }
    }

    private static func searchTokens(_ query: String) -> [String] {
        let separators = CharacterSet.alphanumerics.inverted
        let tokens = query
            .lowercased()
            .components(separatedBy: separators)
            .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
            .filter { $0.count >= 2 }

        return Array(NSOrderedSet(array: tokens)) as? [String] ?? []
    }

    private static func excerpt(_ content: String) -> String {
        let trimmed = content.trimmingCharacters(in: .whitespacesAndNewlines)
        guard trimmed.count > excerptLimit else {
            return trimmed
        }

        return String(trimmed.prefix(excerptLimit)) + "\n[truncated]"
    }

    private static func timestamp(_ date: Date) -> String {
        let formatter = ISO8601DateFormatter()
        formatter.formatOptions = [.withInternetDateTime, .withFractionalSeconds]
        return formatter.string(from: date)
    }
}

private extension String {
    var nilIfEmpty: String? {
        isEmpty ? nil : self
    }
}
