import Testing
@testable import DingDong

struct AppLanguageTests {
    @Test func localizedStringsSupportChineseAndEnglish() {
        #expect(AppLanguage.english.text(.clipboardMonitor) == "Clipboard monitor")
        #expect(AppLanguage.chinese.text(.clipboardMonitor) == "剪贴板监控")
        #expect(CompanionTab.clipboard.title(language: .english) == "Clipboard")
        #expect(CompanionTab.clipboard.title(language: .chinese) == "剪贴板")
        #expect(ResourceType.prompt.displayTitle(language: .english) == "Prompts")
        #expect(ResourceType.prompt.displayTitle(language: .chinese) == "提示词")
        #expect(ResourceType.skill.displayTitle(language: .chinese) == "技能")
        #expect(ClipboardSmartFilter.command.title(language: .chinese) == "命令")
        #expect(ClipboardSmartFilter.sensitive.title(language: .english) == "Sensitive")
        #expect(AppLanguage.english.text(.hotKeyReady) == "⌘⇧V ready")
        #expect(AppLanguage.chinese.message(.apiListening, value: "8765") == "API 正在监听 127.0.0.1:8765")
        #expect(AppLanguage.chinese.text(.apiHistory) == "历史")
        #expect(AppLanguage.english.text(.apiInsights) == "Insights")
        #expect(AppLanguage.chinese.text(.apiInsights) == "洞察")
        #expect(AppLanguage.english.text(.apiSnippets) == "Snippets")
        #expect(AppLanguage.chinese.text(.apiSnippets) == "片段")
        #expect(AppLanguage.english.text(.apiStatus) == "Status")
        #expect(AppLanguage.chinese.text(.apiStatus) == "状态")
        #expect(AppLanguage.english.text(.apiPrepare) == "Prepare")
        #expect(AppLanguage.chinese.text(.apiPrepare) == "准备")
        #expect(AppLanguage.english.text(.apiExport) == "Export")
        #expect(AppLanguage.chinese.text(.apiExport) == "导出")
        #expect(AppLanguage.english.text(.soundTaDa) == "Ta-da")
        #expect(AppLanguage.chinese.text(.soundBubble) == "泡泡")
        #expect(AppLanguage.chinese.text(.soundCoin) == "金币")
        #expect(AppLanguage.english.text(.soundFanfare) == "Fanfare")
        #expect(AppLanguage.chinese.text(.soundArcade) == "街机")
        #expect(AppLanguage.chinese.text(.soundBloom) == "绽放")
        #expect(AppLanguage.english.text(.soundConfetti) == "Confetti")
        #expect(AppLanguage.chinese.text(.soundCandy) == "糖果")
        #expect(AppLanguage.chinese.text(.soundMarimba) == "木琴")
        #expect(AppLanguage.english.text(.soundRandom) == "Random")
        #expect(AppLanguage.chinese.text(.soundRandom) == "随机")
        #expect(AppLanguage.english.text(.activeAgents) == "Active agents")
        #expect(AppLanguage.chinese.text(.noActiveAgents) == "暂无活跃 Agent")
        #expect(AppLanguage.english.text(.agentLaunchpad) == "Agent Launchpad")
        #expect(AppLanguage.chinese.text(.agentLaunchpad) == "Agent 启动台")
        #expect(AppLanguage.english.text(.copyPrepare) == "Prepare")
        #expect(AppLanguage.chinese.text(.copyPresence) == "状态")
        #expect(AppLanguage.english.text(.restoreClipboard) == "Restore clipboard")
        #expect(AppLanguage.chinese.text(.copyResourceID) == "复制 ID")
        #expect(AppLanguage.english.text(.agentMemory) == "Agent memory")
        #expect(AppLanguage.chinese.text(.agentMemory) == "Agent 记忆")
        #expect(AppLanguage.english.text(.copyMemory) == "Copy memory command")
        #expect(AppLanguage.chinese.text(.openMemoryLibrary) == "打开记忆库")
        #expect(AppLanguage.english.text(.clipboardCopilot) == "Clipboard Copilot")
        #expect(AppLanguage.chinese.text(.clipboardCopilot) == "剪贴板 Copilot")
        #expect(AppLanguage.english.text(.clipboardDigestCommand) == "Clipboard Digest")
        #expect(AppLanguage.chinese.text(.hiddenSensitive) == "隐藏敏感")
        #expect(AppLanguage.english.text(.companionReadiness) == "Companion readiness")
        #expect(AppLanguage.chinese.text(.readyForAgents) == "已准备好服务 Agent")
        #expect(AppLanguage.english.text(.agentStartupCommand) == "Agent Startup")
        #expect(AppLanguage.chinese.text(.agentToolkitCommand) == "Agent 工具包命令")
        #expect(AppLanguage.english.text(.agentWorkbench) == "Agent Workbench")
        #expect(AppLanguage.chinese.text(.agentWorkbench) == "Agent 工作台")
        #expect(AppLanguage.english.text(.activeSessions) == "Active sessions")
        #expect(AppLanguage.chinese.text(.noActiveSessions) == "暂无活跃会话")
    }
}
